python create_task.py --name Abalone
python create_task.py --name Adult
python create_task.py --name BreastCancer
python create_task.py --name Churn
python create_task.py --name HeartDisease
python create_task.py --name Sharktank
python create_task.py --name SoybeanLarge
python create_task.py --name Statlog
python create_task.py --name UEFA
python create_task.py --name Wine
python create_task.py --name bank
python create_task.py --name blood
python create_task.py --name calhousing
python create_task.py --name car
python create_task.py --name creditg
python create_task.py --name diabetes
python create_task.py --name heart
python create_task.py --name income
python create_task.py --name jungle
