python xgb_tabpfn.py --seed 0 --use_caafe --data_id 0 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 1 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 2 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 3 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 4 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 5 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 6 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 7 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 8 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 9 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 10 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 0 --use_caafe --data_id 11 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 0 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 1 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 2 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 3 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 4 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 5 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 6 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 7 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 8 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 9 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 10 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 1 --use_caafe --data_id 11 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 0 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 1 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 2 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 3 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 4 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 5 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 6 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 7 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 8 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 9 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 10 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 2 --use_caafe --data_id 11 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 0 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 1 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 2 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 3 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 4 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 5 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 6 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 7 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 8 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 9 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 10 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 3 --use_caafe --data_id 11 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 0 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 1 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 2 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 3 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 4 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 5 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 6 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 7 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 8 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 9 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 10 --cv_folds 5 --val_size 0.2
python xgb_tabpfn.py --seed 4 --use_caafe --data_id 11 --cv_folds 5 --val_size 0.2